name: Master

on:
  push:
    branches:
    - master
    # Ignore changes made by releases
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

env:
  LOG_LEVELS: fatal
  TLS_UNPROTECTED: world

jobs:
  Test-Linux:
    runs-on: ubuntu-18.04

    services:
      mongo:
        image: mongo:3.6.17
        ports:
        - 27017:27017
      consul:
        image: consul:0.9.3
        ports:
        - 8500:8500

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: 12.13.1

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-12.13.1-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run bot

  Test-Windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: 12.13.1

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `%AppData%/npm-cache` on Windows
        path: C:\Users\runneradmin\AppData\Roaming\npm-cache
        key: ${{ runner.os }}-${{ env.cache-name }}-12.13.1-${{ hashFiles('**/package-lock.json') }}

    - name: Install MongoDB 3.6.17
      run: |
        Write-Host "Downloading https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.17.zip ..."
        (New-Object Net.WebClient).DownloadFile(
          "https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.17.zip",
          "C:\mongodb-win32-x86_64-2008plus-ssl-3.6.17.zip"
        )

        Write-Host "Extracting zip archive to C:\mongodb ..."
        Expand-Archive "C:\mongodb-win32-x86_64-2008plus-ssl-3.6.17.zip" -DestinationPath "C:\"
        Rename-Item "C:\mongodb-win32-x86_64-2008plus-ssl-3.6.17" "C:\mongodb"

        Write-Host "Creating necessary folders in C:\mongodb ..."
        mkdir c:\mongodb\data\db | Out-Null
        mkdir c:\mongodb\log | Out-Null

        Write-Host "Writing MongoDB configuration..."
        "systemLog:
          destination: file
          path: c:\mongodb\log\mongod.log
        storage:
          dbPath: c:\mongodb\data\db
        " | Out-File C:\mongodb\mongod.cfg -Encoding utf8

        Write-Host "Creating MonogDB service..."
        cmd /c start /wait sc create MongoDB binPath= "C:\mongodb\bin\mongod.exe --service --config=C:\mongodb\mongod.cfg" DisplayName= "MongoDB" start= "demand"

        Write-Host "Starting MonogDB service..."
        Start-Service mongodb

    - name: Install Consul 0.9.3
      run: |
        choco install --no-progress -y consul --version 0.9.3
        @{
          bind_addr="127.0.0.1"
          bootstrap_expect=1
          ports=@{
            dns=53
            http=8500
          }
          server=$True
        } | ConvertTo-Json | Out-File -Filepath C:\ProgramData\consul\config\config.json -Encoding ascii
        Restart-Service consul

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run bot

  Release:
    needs:
    - Test-Linux
    - Test-Windows

    runs-on: ubuntu-18.04

    env:
      GIT_AUTHOR_EMAIL: com.git@sealsystems.de
      GIT_AUTHOR_NAME: CI Build
      GIT_COMMITTER_EMAIL: com.git@sealsystems.de
      GIT_COMMITTER_NAME: CI Build
      # Use personal access token for creating releases on GitHub
      GITHUB_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
      # Use personal access token for publishing on GitHub Packages
      NPM_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Use personal access token for cloning (and later pushing) code
        token: ${{ secrets.GITHUB_CI_TOKEN }}

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: ${{ env.NODE_VERSION }}

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Trigger release
      run: npm run release
